# Generated by Django 4.2.9 on 2024-02-29 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('landingpage', '0002_alter_categoria_options_alter_empresa_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_air', models.BooleanField(default=False, help_text='Indica se a página está no ar.')),
                ('titulo', models.CharField(help_text='Tema central na página', max_length=100)),
                ('paragrafo', models.TextField(help_text='Parágrafo de boas vindas', max_length=600)),
                ('produtos', models.TextField(help_text='Informações do produto passadas no formato Json. Ex: {"pizza": ["Pizza de Calabresa", "Calabresa, Queijo Chedar e massa especial", 59.90, "nome_do_arquivo"]}')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='landingpage.empresa')),
            ],
            options={
                'verbose_name': '   Store',
                'verbose_name_plural': '   Stores',
            },
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.store')),
            ],
            options={
                'verbose_name': '  Shelf',
                'verbose_name_plural': '  Shelves',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('shelf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.shelf')),
            ],
            options={
                'verbose_name': ' Item',
                'verbose_name_plural': ' Items',
            },
        ),
        migrations.CreateModel(
            name='Hub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_air', models.BooleanField(default=False, help_text='Indica se a página está no ar.')),
                ('nome', models.CharField(help_text='Nome do Food Park centralizador', max_length=100)),
                ('slogam', models.CharField(help_text='Slogam do Food Park centralizador', max_length=100)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='landingpage.empresa')),
                ('lojas', models.ManyToManyField(to='loja.store')),
            ],
            options={
                'verbose_name': 'Concentrador',
                'verbose_name_plural': 'Concentradores',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.cart')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.item')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(through='loja.CartItem', to='loja.item'),
        ),
        migrations.AddField(
            model_name='cart',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.store'),
        ),
    ]
