# Generated by Django 4.2.9 on 2024-03-21 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hub',
            name='url',
            field=models.CharField(db_index=True, editable=False, help_text='Endereço de url da página.', max_length=60),
        ),
        migrations.AlterField(
            model_name='store',
            name='url',
            field=models.CharField(db_index=True, editable=False, help_text='Endereço de url da página.', max_length=60),
        ),
    ]
