# Generated by Django 4.2.9 on 2024-02-29 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='shelf',
            new_name='_shelf',
        ),
    ]
