# Generated by Django 4.2.9 on 2024-02-05 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_air', models.BooleanField(help_text='Indica se a página está no ar.')),
                ('url', models.CharField(help_text='O endereço final do link da página', max_length=50)),
                ('meta_description', models.CharField(blank=True, help_text='Uma descrição que vai aparecer para o usuário durante a busca', max_length=160)),
                ('lojas', models.ManyToManyField(to='loja.loja')),
            ],
            options={
                'verbose_name': 'Registro de Hub',
                'verbose_name_plural': 'Registros de Hubs',
            },
        ),
    ]
