# Generated by Django 4.2.9 on 2024-03-01 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_rename_shelf_item_shelf_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='shelf_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loja.shelf'),
        ),
    ]
