# Generated by Django 4.2.9 on 2024-02-25 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0015_empresa_g_business_empresa_g_embbedmaps'),
        ('loja', '0002_alter_item_description_productcategory_cart_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loja',
            name='slogam',
        ),
        migrations.AddField(
            model_name='loja',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='landingpage.empresa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loja',
            name='paragrafo',
            field=models.TextField(help_text='Parágrafo de boas vindas', max_length=600),
        ),
    ]
