# Generated by Django 4.2.9 on 2024-02-22 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_alter_hub_redes_sociais_alter_loja_redes_sociais'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hub',
            name='redes_sociais',
        ),
        migrations.RemoveField(
            model_name='loja',
            name='redes_sociais',
        ),
    ]
