# Generated by Django 4.2.9 on 2024-02-05 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_hub'),
    ]

    operations = [
        migrations.AddField(
            model_name='hub',
            name='nome',
            field=models.CharField(default='unknown', help_text='Nome do Food Park centralizador', max_length=100),
            preserve_default=False,
        ),
    ]
