# Generated by Django 4.2.9 on 2024-02-29 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_rename_shelf_item__shelf'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='imagem_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
