# Generated by Django 4.2.9 on 2024-02-05 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_hub_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='hub',
            name='slogam',
            field=models.CharField(default='unknown', help_text='Slogam do Food Park centralizador', max_length=100),
            preserve_default=False,
        ),
    ]
