# Generated by Django 4.2.9 on 2024-02-25 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0016_alter_landingpage_options_and_more'),
        ('loja', '0003_remove_loja_slogam_loja_empresa_alter_loja_paragrafo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hub',
            name='link_facebook',
        ),
        migrations.RemoveField(
            model_name='hub',
            name='link_instagram',
        ),
        migrations.RemoveField(
            model_name='hub',
            name='link_whats',
        ),
        migrations.RemoveField(
            model_name='hub',
            name='nome_empresa',
        ),
        migrations.RemoveField(
            model_name='loja',
            name='link_facebook',
        ),
        migrations.RemoveField(
            model_name='loja',
            name='link_instagram',
        ),
        migrations.RemoveField(
            model_name='loja',
            name='link_whats',
        ),
        migrations.RemoveField(
            model_name='loja',
            name='nome_empresa',
        ),
        migrations.AddField(
            model_name='hub',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='landingpage.empresa'),
            preserve_default=False,
        ),
    ]
