# Generated by Django 4.2.9 on 2024-03-13 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_rename_shelf_to_item_shelf'),
    ]

    operations = [
        migrations.AddField(
            model_name='hub',
            name='url',
            field=models.CharField(default=1, help_text='Endereço de url da página.', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='url',
            field=models.CharField(default=1, help_text='Endereço de url da página.', max_length=30),
            preserve_default=False,
        ),
    ]
