# Generated by Django 4.2.9 on 2024-02-25 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_remove_hub_link_facebook_remove_hub_link_instagram_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hub',
            name='url',
        ),
        migrations.RemoveField(
            model_name='loja',
            name='url',
        ),
    ]
