# Generated by Django 4.2.9 on 2024-02-07 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_hub_slogam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loja',
            name='produtos',
            field=models.TextField(help_text='Informações do produto passadas no formato Json. Ex: {"pizza": ["Pizza de Calabresa", "Calabresa, Queijo Chedar e massa especial", 59.90, "nome_do_arquivo"]}'),
        ),
    ]
