# Generated by Django 4.2.9 on 2024-02-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0005_alter_loja_produtos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loja',
            name='endereco_bucket',
        ),
        migrations.RemoveField(
            model_name='loja',
            name='url_cadastrado',
        ),
        migrations.AddField(
            model_name='hub',
            name='link_facebook',
            field=models.URLField(blank=True, help_text='Link para a página do facebook'),
        ),
        migrations.AddField(
            model_name='hub',
            name='link_instagram',
            field=models.URLField(blank=True, help_text='Link para a página do instagram'),
        ),
        migrations.AddField(
            model_name='hub',
            name='link_whats',
            field=models.URLField(blank=True, help_text='https://api.whatsapp.com/send?phone=5199876543'),
        ),
        migrations.AddField(
            model_name='hub',
            name='nome_empresa',
            field=models.CharField(default=1, help_text='Nome da empresa, da loja ou do concentrador', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loja',
            name='url',
            field=models.CharField(default=1, help_text='A parte personalizada do endereço no final do link da página', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hub',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Descrição do site que vai aparecer para o usuário durante a busca.', max_length=160),
        ),
        migrations.AlterField(
            model_name='hub',
            name='url',
            field=models.CharField(help_text='A parte personalizada do endereço no final do link da página', max_length=50),
        ),
        migrations.AlterField(
            model_name='loja',
            name='link_facebook',
            field=models.URLField(blank=True, help_text='Link para a página do facebook'),
        ),
        migrations.AlterField(
            model_name='loja',
            name='link_instagram',
            field=models.URLField(blank=True, help_text='Link para a página do instagram'),
        ),
        migrations.AlterField(
            model_name='loja',
            name='link_whats',
            field=models.URLField(blank=True, help_text='https://api.whatsapp.com/send?phone=5199876543'),
        ),
        migrations.AlterField(
            model_name='loja',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Descrição do site que vai aparecer para o usuário durante a busca.', max_length=160),
        ),
        migrations.AlterField(
            model_name='loja',
            name='nome_empresa',
            field=models.CharField(help_text='Nome da empresa, da loja ou do concentrador', max_length=50),
        ),
    ]
