# Generated by Django 4.2.9 on 2024-02-15 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0006_remove_loja_endereco_bucket_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hub',
            name='link_whats',
            field=models.URLField(blank=True, help_text='https://api.whatsapp.com/send?phone='),
        ),
        migrations.AlterField(
            model_name='hub',
            name='on_air',
            field=models.BooleanField(default=False, help_text='Indica se a página está no ar.'),
        ),
        migrations.AlterField(
            model_name='loja',
            name='link_whats',
            field=models.URLField(blank=True, help_text='https://api.whatsapp.com/send?phone='),
        ),
        migrations.AlterField(
            model_name='loja',
            name='on_air',
            field=models.BooleanField(default=False, help_text='Indica se a página está no ar.'),
        ),
    ]
