# Generated by Django 4.2.9 on 2024-03-14 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0006_alter_hub_url_alter_store_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hub',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='hub',
            name='slogam',
        ),
    ]
