# Generated by Django 4.2.9 on 2024-02-16 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0007_alter_hub_link_whats_alter_hub_on_air_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hub',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='loja',
            name='meta_description',
        ),
    ]
