# Generated by Django 4.2.9 on 2024-03-16 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0008_remove_hub_on_air_remove_hub_url_item_image_filename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
