# Generated by Django 4.2.9 on 2024-03-16 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0009_remove_cartitem_cart_delete_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='hub',
            name='on_air',
            field=models.BooleanField(default=False, help_text='Indica se a página está no ar.'),
        ),
        migrations.AddField(
            model_name='hub',
            name='url',
            field=models.CharField(default=1, editable=False, help_text='Endereço de url da página.', max_length=30),
            preserve_default=False,
        ),
    ]
