# Generated by Django 4.2.9 on 2024-03-21 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0010_hub_on_air_hub_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hub',
            name='on_air',
            field=models.BooleanField(db_index=True, default=False, help_text='Indica se a página está no ar.'),
        ),
        migrations.AlterField(
            model_name='hub',
            name='url',
            field=models.CharField(db_index=True, editable=False, help_text='Endereço de url da página.', max_length=30),
        ),
        migrations.AlterField(
            model_name='store',
            name='on_air',
            field=models.BooleanField(db_index=True, default=False, help_text='Indica se a página está no ar.'),
        ),
        migrations.AlterField(
            model_name='store',
            name='url',
            field=models.CharField(db_index=True, editable=False, help_text='Endereço de url da página.', max_length=30),
        ),
    ]
