# Generated by Django 4.2.9 on 2024-01-13 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContadorAJRCutelaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contagem', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ContadorCatalogoDigital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contagem', models.IntegerField(default=0)),
            ],
        ),
    ]
