# Generated by Django 4.2.9 on 2024-01-13 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageViewsCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('value', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='ContadorAJRCutelaria',
        ),
        migrations.DeleteModel(
            name='ContadorCatalogoDigital',
        ),
    ]
