# Generated by Django 4.2.9 on 2024-01-14 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_pageviewscounter_delete_contadorajrcutelaria_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageViewsCounter',
        ),
    ]
