# Generated by Django 4.2.9 on 2024-02-22 00:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Categoria de Serviço',
                'verbose_name_plural': 'Categorias de Serviços',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='LandingPagePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('can_access_own_products', 'Can Access Own Products')],
            },
        ),
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_air', models.BooleanField(default=False, help_text='Indica se a página está no ar.')),
                ('url', models.CharField(help_text='A parte personalizada do endereço no final do link da página', max_length=50)),
                ('link_whats', models.URLField(blank=True, help_text='https://api.whatsapp.com/send?phone=')),
                ('link_facebook', models.URLField(blank=True, help_text='Link para a página do facebook')),
                ('link_instagram', models.URLField(blank=True, help_text='Link para a página do instagram')),
                ('nome_empresa', models.CharField(help_text='Nome da empresa, da loja ou do concentrador', max_length=50)),
                ('redes_sociais', models.TextField(blank=True, help_text='Links das redes sociais separados por linha', max_length=500)),
                ('descricao_curta', models.CharField(help_text='Texto acima do nome da empresa(SubHeader). Síntese da atividade principal. (Obrigatório conter as PALAVRAS CHAVES)', max_length=100)),
                ('trend_words', models.CharField(help_text='Palavras chaves consultadas no Google Trend', max_length=500)),
                ('lista_items', models.TextField(blank=True, default='[]', help_text='Seção de lista da página. Um item por linha.', max_length=600)),
                ('colunas_items', models.TextField(blank=True, default='{}', help_text='Seção de colunas da página. Dict no formato {"Título1":"Conteúdo1","Título2":"Conteúdo2"},...')),
                ('numeros_telefone', models.CharField(blank=True, help_text='Ex: (12) 98765 4321 (São permitidos múltiplos números)', max_length=50)),
                ('email_contato', models.EmailField(blank=True, help_text='Ex: nome@empresa.com.br', max_length=254)),
                ('endereco', models.CharField(blank=True, help_text='Ex: Rua Duque de Caxias, 237, Centenário, Sapiranga - RS', max_length=100)),
                ('horario_atendimento', models.CharField(blank=True, help_text='Ex: Seg à Sex das 10h as 17h.', max_length=100)),
                ('carousel_size', models.IntegerField(help_text='Quantidade de imagens no carossel da página.')),
                ('link_loja', models.CharField(blank=True, help_text='Nome do botão e link para para site externo. Conheça nossa Loja Virtual#https://minhaloja.com.br', max_length=150)),
                ('reviews_link', models.URLField(blank=True, help_text='Link obtido abrindo o google empresas e clicando em Share > Send a link. Ex: https://maps.app.goo.gl/pTZvag2fg7ytV74eA')),
                ('gmaps_link', models.CharField(blank=True, help_text='Link obtido abrindo o google empresas e clicando em Share > Embed a map > Small.', max_length=500)),
                ('categoria_servico', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='landingpage.categoriaservico')),
                ('cidades', models.ManyToManyField(to='landingpage.cidade')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Landing Page',
                'verbose_name_plural': 'Registros de Landing Pages',
                'ordering': ['-on_air', 'nome_empresa'],
            },
        ),
        migrations.AddIndex(
            model_name='cidade',
            index=models.Index(fields=['nome'], name='landingpage_nome_7422eb_idx'),
        ),
        migrations.AddIndex(
            model_name='categoriaservico',
            index=models.Index(fields=['nome'], name='landingpage_nome_042238_idx'),
        ),
        migrations.AddIndex(
            model_name='landingpage',
            index=models.Index(fields=['url'], name='landingpage_url_f17cf1_idx'),
        ),
        migrations.AddIndex(
            model_name='landingpage',
            index=models.Index(fields=['on_air'], name='landingpage_on_air_6e36d3_idx'),
        ),
    ]
