# Generated by Django 4.2.9 on 2024-03-01 02:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import landingpage.model_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': '     Ramos de atuação',
                'verbose_name_plural': '     Ramos de atuação',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome da empresa', max_length=100)),
                ('tagline', models.CharField(help_text='Texto em destaque que descreve a essência da marca.', max_length=50)),
                ('address', models.CharField(help_text='Precisa conter no mínimo: Bairro, Cidade - DF', max_length=255)),
                ('opening_hours', models.CharField(help_text='Exemplo: Seg à Sex das 10h as 17h.', max_length=100)),
                ('phone_numbers', models.CharField(help_text='Um ou mais números no modelo (11) 99887 6543 separados por vírgula.', max_length=50)),
                ('is_whatsapp', models.BooleanField(help_text='Indica se o primeiro número informado é um contato do whatsapp.')),
                ('e_mail', models.EmailField(blank=True, help_text='Email da empresa', max_length=40)),
                ('social_media', landingpage.model_fields.MultipleURLsField(blank=True, help_text='Links das redes sociais separados por vírgula.', max_length=250)),
                ('g_business', models.URLField(blank=True, help_text='Link obtido abrindo o google empresas e clicando em Share > Send a link. Ex: https://maps.app.goo.gl/pTZvag2fg7ytV74eA', max_length=50)),
                ('g_embbedmaps', models.CharField(blank=True, help_text='Link obtido abrindo o google empresas e clicando em Share > Embed a map > Small.', max_length=500)),
                ('website', models.CharField(blank=True, help_text='Nome do botão e link para para site. Ex. Conheça nossa Loja Virtual # https://minhaloja.com.br', max_length=150)),
                ('category', models.ForeignKey(help_text='Categoria dos serviços que a empresa oferece.', on_delete=django.db.models.deletion.PROTECT, to='landingpage.categoria')),
                ('employees', models.ManyToManyField(blank=True, help_text='Funcionários da empresa.', related_name='employees', to=settings.AUTH_USER_MODEL)),
                ('owners', models.ManyToManyField(help_text='Usuários que terão acesso de editor.', related_name='owners', to=settings.AUTH_USER_MODEL)),
                ('service_areas', models.ManyToManyField(to='landingpage.cidade')),
            ],
            options={
                'verbose_name': '     Empresa',
                'verbose_name_plural': '     Empresas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('duracao', models.IntegerField()),
            ],
            options={
                'verbose_name': '     Serviço sob agendamento',
                'verbose_name_plural': '    Serviços sob agendamento',
            },
        ),
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_air', models.BooleanField(default=False, help_text='Indica se a página está no ar.')),
                ('lista_items', models.TextField(blank=True, default='[]', help_text='Seção de lista da página. Um item por linha.', max_length=600)),
                ('colunas_items', models.TextField(blank=True, default='{}', help_text='Seção de colunas da página. Dict no formato {"Título1":"Conteúdo1","Título2":"Conteúdo2"},...')),
                ('carousel_size', models.IntegerField(help_text='Quantidade de imagens no carossel da página.')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='landingpage.empresa')),
            ],
            options={
                'verbose_name': '    Landing Page',
                'verbose_name_plural': '   Landing Pages',
            },
        ),
        migrations.AddIndex(
            model_name='cidade',
            index=models.Index(fields=['nome'], name='landingpage_nome_7422eb_idx'),
        ),
        migrations.AddIndex(
            model_name='categoria',
            index=models.Index(fields=['nome'], name='landingpage_nome_1b2368_idx'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landingpage.cliente'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landingpage.servico'),
        ),
        migrations.AddIndex(
            model_name='landingpage',
            index=models.Index(fields=['on_air'], name='landingpage_on_air_6e36d3_idx'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['name'], name='landingpage_name_a52bb7_idx'),
        ),
    ]
