# Generated by Django 4.2.9 on 2024-03-09 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoria',
            new_name='Category',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': '     Ramos de atuação', 'verbose_name_plural': '     Ramos de atuação'},
        ),
        migrations.AlterModelOptions(
            name='landingpage',
            options={'ordering': ['-on_air', 'empresa'], 'verbose_name': '    Landing Page', 'verbose_name_plural': '   Landing Pages'},
        ),
        migrations.RemoveIndex(
            model_name='category',
            name='landingpage_nome_1b2368_idx',
        ),
        migrations.RemoveIndex(
            model_name='landingpage',
            name='landingpage_on_air_6e36d3_idx',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='nome',
            new_name='name',
        ),
    ]
