# Generated by Django 4.2.9 on 2024-02-22 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpage',
            name='redes_sociais',
            field=models.TextField(help_text='Links das redes sociais separados por linha'),
        ),
    ]
