# Generated by Django 4.2.9 on 2024-02-29 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nome'], 'verbose_name': '     Ramos de atuação', 'verbose_name_plural': '     Ramos de atuação'},
        ),
        migrations.AlterModelOptions(
            name='empresa',
            options={'ordering': ['name'], 'verbose_name': '     Empresa', 'verbose_name_plural': '     Empresas'},
        ),
        migrations.AlterModelOptions(
            name='landingpage',
            options={'verbose_name': '    Landing Page', 'verbose_name_plural': '   Landing Pages'},
        ),
        migrations.AlterModelOptions(
            name='servico',
            options={'verbose_name': '     Serviço sob agendamento', 'verbose_name_plural': '    Serviços sob agendamento'},
        ),
    ]
