# Generated by Django 4.2.9 on 2024-02-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repositorio_imagens', models.CharField(help_text='https://gjvoxpezczvyqbnmonap.supabase.co/storage/v1/object/public/conecta_bucket/', max_length=200)),
            ],
            options={
                'verbose_name': 'Configuração do Sistema',
                'verbose_name_plural': 'Configurações do Sistema',
            },
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='nomes_arquivos_imagens',
            field=models.CharField(blank=True, help_text='Nomes dos arquivos de imagens(sem a extensão)                                               separados por virgula. Um arquivo para a capa, em baixa qualidade, um para a capa em                                               alta qualidade e o restante para o carousel.', max_length=300),
        ),
    ]
