# Generated by Django 4.2.9 on 2024-02-18 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpage',
            name='endereco',
            field=models.CharField(blank=True, help_text='Ex: Rua Duque de Caxias, 237, Centenário, Sapiranga - RS', max_length=100),
        ),
    ]
