# Generated by Django 4.2.9 on 2024-02-22 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0002_alter_landingpage_redes_sociais'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landingpage',
            name='redes_sociais',
        ),
    ]
