# Generated by Django 4.2.9 on 2024-02-06 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0002_sistema_alter_landingpage_nomes_arquivos_imagens'),
    ]

    operations = [
        migrations.AddField(
            model_name='sistema',
            name='config_name',
            field=models.CharField(default=0, help_text='Nome da configuração do sistema', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sistema',
            name='on_air',
            field=models.BooleanField(default=1, help_text='Indica se a configuração está ativa'),
            preserve_default=False,
        ),
    ]
