# Generated by Django 4.2.9 on 2024-03-13 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0002_rename_categoria_category_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='url',
            field=models.CharField(default=1, help_text='Endereço de url da página.', max_length=30),
            preserve_default=False,
        ),
    ]
