# Generated by Django 4.2.9 on 2024-02-16 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0002_landingpage_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriaservico',
            options={'ordering': ['nome'], 'verbose_name': 'Categoria de Serviço', 'verbose_name_plural': 'Categorias de Serviços'},
        ),
        migrations.AlterModelOptions(
            name='cidade',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='landingpage',
            options={'ordering': ['-on_air', 'nome_empresa'], 'verbose_name': 'Registro de Landing Page', 'verbose_name_plural': 'Registros de Landing Pages'},
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='gmaps_link',
            field=models.URLField(blank=True, help_text='Link obtido abrindo o google empresas e clicando em Share > Embed a map > Small.', max_length=500),
        ),
    ]
