# Generated by Django 4.2.9 on 2024-02-24 01:53

from django.db import migrations
import landingpage.models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0002_cliente_empresa_servico_funcionario_agendamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='links_redes_sociais',
            field=landingpage.models.MultipleURLsField(default=1),
            preserve_default=False,
        ),
    ]
