# Generated by Django 4.2.9 on 2024-03-21 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0002_alter_landingpage_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='heading_style',
            field=models.IntegerField(blank=True, choices=[(1, 'Preto'), (2, 'Azul'), (3, 'Texto sobre a imagem'), (4, 'Texto na imagem')], null=True),
        ),
    ]
