# Generated by Django 4.2.9 on 2024-02-19 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0002_alter_landingpage_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpage',
            name='link_loja',
            field=models.CharField(blank=True, help_text='Nome do botão e link para para site externo. Conheça nossa Loja Virtual#https://minhaloja.com.br', max_length=150),
        ),
    ]
