# Generated by Django 4.2.9 on 2024-02-07 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0003_sistema_config_name_sistema_on_air'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landingpage',
            name='endereco_bucket',
        ),
    ]
