# Generated by Django 4.2.9 on 2024-02-20 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0003_alter_landingpage_link_loja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpage',
            name='lista_items',
            field=models.TextField(blank=True, default='[]', help_text='Seção de lista da página. Um item por linha.', max_length=600),
        ),
    ]
