# Generated by Django 4.2.9 on 2024-02-16 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0003_alter_categoriaservico_options_alter_cidade_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpage',
            name='gmaps_link',
            field=models.CharField(blank=True, help_text='Link obtido abrindo o google empresas e clicando em Share > Embed a map > Small.', max_length=500),
        ),
    ]
