# Generated by Django 4.2.9 on 2024-02-24 02:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import landingpage.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('landingpage', '0003_empresa_links_redes_sociais'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='categoria_servico',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='landingpage.categoriaservico'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='celular_whats',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='empresa',
            name='horario_atendimento',
            field=models.CharField(blank=True, help_text='Ex: Seg à Sex das 10h as 17h.', max_length=100),
        ),
        migrations.AddField(
            model_name='empresa',
            name='responsaveis',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='email',
            field=models.EmailField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='links_redes_sociais',
            field=landingpage.models.MultipleURLsField(blank=True, help_text='Links das redes sociais separados por vírgula.'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='telefone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
