# Generated by Django 4.2.9 on 2024-02-24 02:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import landingpage.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('landingpage', '0004_empresa_categoria_servico_empresa_celular_whats_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'ordering': ['nome'], 'verbose_name': 'Registro de Empresa', 'verbose_name_plural': 'Registros de Empresas'},
        ),
        migrations.AlterField(
            model_name='empresa',
            name='categoria_servico',
            field=models.ForeignKey(help_text='Categoria dos serviços que a empresa oferece.', on_delete=django.db.models.deletion.PROTECT, to='landingpage.categoriaservico'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='celular_whats',
            field=models.CharField(blank=True, help_text='55 11 99988 7766', max_length=20),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='descricao',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='email',
            field=models.EmailField(blank=True, help_text='Email da empresa', max_length=40),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='endereco',
            field=models.CharField(help_text='Rua, número, Bairro, Cidade - DF', max_length=255),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='horario_atendimento',
            field=models.CharField(blank=True, help_text='Exemplo: Seg à Sex das 10h as 17h.', max_length=100),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='links_redes_sociais',
            field=landingpage.models.MultipleURLsField(blank=True, help_text='Links das redes sociais separados por vírgula.', max_length=250),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nome',
            field=models.CharField(help_text='Nome da empresa', max_length=100),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='responsaveis',
            field=models.ManyToManyField(help_text='Usuários que terão acesso aos produtos desta empresa.', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='telefone',
            field=models.CharField(blank=True, help_text='(11) 3212 4567', max_length=20),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['nome'], name='landingpage_nome_8e449e_idx'),
        ),
    ]
