# Generated by Django 4.2.9 on 2024-02-25 14:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('landingpage', '0005_alter_empresa_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'ordering': ['name'], 'verbose_name': 'Cadastro de Negócio', 'verbose_name_plural': 'Cadastros de Negócios'},
        ),
        migrations.RemoveIndex(
            model_name='empresa',
            name='landingpage_nome_8e449e_idx',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='endereco',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='categoria_servico',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='nome',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='celular_whats',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='responsaveis',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='telefone',
        ),
        migrations.AddField(
            model_name='empresa',
            name='is_whatsapp',
            field=models.BooleanField(blank=True, default=1, help_text='Indica se o primeiro número informado é um contato do whatsapp.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='owners',
            field=models.ManyToManyField(help_text='Usuários que terão acesso de editor.', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empresa',
            name='phone_numbers',
            field=models.CharField(blank=True, help_text='Um ou mais números no modelo 55 11 99887 6543 separados por vírgula.', max_length=50),
        ),
        migrations.AlterField(
            model_name='cidade',
            name='nome',
            field=models.CharField(max_length=50),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['name'], name='landingpage_name_a52bb7_idx'),
        ),
    ]
