# Generated by Django 4.2.9 on 2024-02-08 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0005_delete_sistema_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landingpage',
            name='lista_titulo',
        ),
    ]
