# Generated by Django 4.2.9 on 2024-02-08 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0006_remove_landingpage_lista_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpage',
            name='link_loja',
            field=models.TextField(blank=True, help_text='Nome do botão e link para a loja no formato key:value', max_length=150),
        ),
    ]
