# Generated by Django 4.2.9 on 2024-02-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0006_alter_empresa_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='email',
            new_name='e_mails',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='horario_atendimento',
            new_name='opening_hours',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='links_redes_sociais',
            new_name='social_media_links',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='landingpage',
            name='trend_words',
        ),
        migrations.AddField(
            model_name='empresa',
            name='tagline',
            field=models.TextField(blank=True, help_text='Texto em destaque que descreve a essência da marca.', max_length=50),
        ),
    ]
