# Generated by Django 4.2.9 on 2024-02-25 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0007_rename_email_empresa_e_mails_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'ordering': ['name'], 'verbose_name': 'Cadastro de Negócio', 'verbose_name_plural': 'Cadastro de Negócios'},
        ),
        migrations.AlterField(
            model_name='empresa',
            name='tagline',
            field=models.CharField(blank=True, help_text='Texto em destaque que descreve a essência da marca.', max_length=50),
        ),
    ]
