# Generated by Django 4.2.9 on 2024-02-25 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0008_alter_empresa_options_alter_empresa_tagline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='address',
            field=models.CharField(help_text='Precisa conter no mínimo: Bairro, Cidade - DF', max_length=255),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='is_whatsapp',
            field=models.BooleanField(help_text='Indica se o primeiro número informado é um contato do whatsapp.'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='opening_hours',
            field=models.CharField(help_text='Exemplo: Seg à Sex das 10h as 17h.', max_length=100),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='phone_numbers',
            field=models.CharField(help_text='Um ou mais números no modelo 55 11 99887 6543 separados por vírgula.', max_length=50),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='tagline',
            field=models.CharField(help_text='Texto em destaque que descreve a essência da marca.', max_length=50),
        ),
    ]
