# Generated by Django 4.2.9 on 2024-02-09 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0008_landingpage_resumo_chave_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='cidade',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='colunas_items',
            field=models.TextField(blank=True, help_text='SEeão de colunas da página. Dict no formato {"Título1":"Conteúdo1","Título2":"Conteúdo2"},...'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='descricao_curta',
            field=models.CharField(help_text='Texto acima do nome da empresa(SubHeader). Síntese da atividade principal. (Obrigatório conter as PALAVRAS CHAVES)', max_length=100),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='email_contato',
            field=models.EmailField(blank=True, help_text='Ex: nome@empresa.com.br', max_length=254),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='endereco',
            field=models.CharField(blank=True, help_text='Ex: Rua Duque de Caxias, 237', max_length=100),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='gmaps_link',
            field=models.URLField(blank=True, help_text='Link obtido abrindo o google empresas e clicando em Share > Embed a map > Small.', max_length=500),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='horario_atendimento',
            field=models.CharField(blank=True, help_text='Ex: Seg à Sex das 10h as 17h.', max_length=100),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='link_loja',
            field=models.TextField(blank=True, help_text='Nome do botão e link para para site externo. Dict no formato {"Conheça nossa Loja Virtual":"https://minhaloja.com.br" }', max_length=150),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='lista_items',
            field=models.TextField(blank=True, help_text='Seção de lista da página. Dict no formato {"Título da lista": ["item1","item2",...]', max_length=600),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='numeros_telefone',
            field=models.CharField(blank=True, help_text='Ex: (12) 98765 4321 (São permitidos múltiplos números)', max_length=50),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='resumo_chave',
            field=models.TextField(help_text='Este resumo deve ser uma descrição bem clara e objetiva (Obrigatório conter variações das PALAVRAS CHAVES e o NOME DA CIDADE).', max_length=300),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='reviews_link',
            field=models.URLField(blank=True, help_text='Link obtido abrindo o google empresas e clicando em Share > Send a link. Ex: https://maps.app.goo.gl/pTZvag2fg7ytV74eA'),
        ),
    ]
