# Generated by Django 4.2.9 on 2024-02-09 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0009_landingpage_cidade_alter_landingpage_colunas_items_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpage',
            name='gmaps_link',
            field=models.CharField(blank=True, help_text='Link obtido abrindo o google empresas e clicando em Share > Embed a map > Small.', max_length=500),
        ),
    ]
