# Generated by Django 4.2.9 on 2024-02-25 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0009_alter_empresa_address_alter_empresa_is_whatsapp_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoriaServico',
            new_name='Categoria',
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nome'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.RenameIndex(
            model_name='categoria',
            new_name='landingpage_nome_1b2368_idx',
            old_name='landingpage_nome_042238_idx',
        ),
    ]
