# Generated by Django 4.2.9 on 2024-02-25 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0011_rename_e_mails_empresa_e_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='service_areas',
            field=models.ManyToManyField(to='landingpage.cidade'),
        ),
    ]
