# Generated by Django 4.2.9 on 2024-02-15 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0011_landingpage_trend_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpage',
            name='colunas_items',
            field=models.TextField(default='{}', help_text='SEeão de colunas da página. Dict no formato {"Título1":"Conteúdo1","Título2":"Conteúdo2"},...'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='link_loja',
            field=models.TextField(blank=True, default='{}', help_text='Nome do botão e link para para site externo. Dict no formato {"Conheça nossa Loja Virtual":"https://minhaloja.com.br" }', max_length=150),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='link_whats',
            field=models.URLField(blank=True, help_text='https://api.whatsapp.com/send?phone='),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='lista_items',
            field=models.TextField(default='{}', help_text='Seção de lista da página. Dict no formato {"Título da lista": ["item1","item2",...]', max_length=600),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='on_air',
            field=models.BooleanField(default=False, help_text='Indica se a página está no ar.'),
        ),
    ]
