# Generated by Django 4.2.9 on 2024-02-25 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0012_empresa_service_areas'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='landingpage.empresa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='categoria_servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='landingpage.categoria'),
        ),
    ]
