# Generated by Django 4.2.9 on 2024-02-15 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0012_alter_landingpage_colunas_items_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='landingpage',
            name='cidade',
        ),
        migrations.AddField(
            model_name='landingpage',
            name='cidades',
            field=models.ManyToManyField(to='landingpage.cidade'),
        ),
    ]
