# Generated by Django 4.2.9 on 2024-02-25 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0013_landingpage_empresa_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='social_media_links',
            new_name='social_media',
        ),
    ]
