# Generated by Django 4.2.9 on 2024-02-25 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0014_rename_social_media_links_empresa_social_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='g_business',
            field=models.URLField(blank=True, help_text='Link obtido abrindo o google empresas e clicando em Share > Send a link. Ex: https://maps.app.goo.gl/pTZvag2fg7ytV74eA', max_length=50),
        ),
        migrations.AddField(
            model_name='empresa',
            name='g_embbedmaps',
            field=models.CharField(blank=True, help_text='Link obtido abrindo o google empresas e clicando em Share > Embed a map > Small.', max_length=500),
        ),
    ]
