# Generated by Django 4.2.9 on 2024-02-15 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0014_categoriaservico'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriaservico',
            options={'verbose_name': 'Categoria de Serviço', 'verbose_name_plural': 'Categorias de Serviços'},
        ),
        migrations.AddField(
            model_name='landingpage',
            name='categoria_servico',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='landingpage.categoriaservico'),
            preserve_default=False,
        ),
    ]
