# Generated by Django 4.2.9 on 2024-02-15 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0015_alter_categoriaservico_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpage',
            name='categoria_servico',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='landingpage.categoriaservico'),
        ),
    ]
