# Generated by Django 4.2.9 on 2024-02-25 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0015_empresa_g_business_empresa_g_embbedmaps'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='landingpage',
            options={'verbose_name': 'Registro de Landing Page', 'verbose_name_plural': 'Registros de Landing Pages'},
        ),
        migrations.RemoveField(
            model_name='landingpage',
            name='link_facebook',
        ),
        migrations.RemoveField(
            model_name='landingpage',
            name='link_instagram',
        ),
        migrations.RemoveField(
            model_name='landingpage',
            name='link_whats',
        ),
        migrations.RemoveField(
            model_name='landingpage',
            name='nome_empresa',
        ),
    ]
