# Generated by Django 4.2.9 on 2024-02-25 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0016_alter_landingpage_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='landingpage',
            name='landingpage_url_f17cf1_idx',
        ),
        migrations.RemoveField(
            model_name='landingpage',
            name='url',
        ),
        migrations.AlterField(
            model_name='empresa',
            name='phone_numbers',
            field=models.CharField(help_text='Um ou mais números no modelo (11) 99887 6543 separados por vírgula.', max_length=50),
        ),
    ]
