# Generated by Django 4.2.9 on 2024-02-16 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0016_alter_landingpage_categoria_servico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landingpage',
            name='meta_description',
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='colunas_items',
            field=models.TextField(blank=True, default='{}', help_text='Seção de colunas da página. Dict no formato {"Título1":"Conteúdo1","Título2":"Conteúdo2"},...'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='lista_items',
            field=models.TextField(blank=True, default='{}', help_text='Seção de lista da página. Dict no formato {"Título da lista": ["item1","item2",...]', max_length=600),
        ),
    ]
