# Generated by Django 4.2.9 on 2024-02-16 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0017_remove_landingpage_meta_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landingpage',
            name='resumo_chave',
        ),
    ]
