# Generated by Django 4.2.9 on 2024-02-27 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0017_remove_landingpage_landingpage_url_f17cf1_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landingpage',
            name='categoria_servico',
        ),
        migrations.RemoveField(
            model_name='landingpage',
            name='cidades',
        ),
        migrations.RemoveField(
            model_name='landingpage',
            name='descricao_curta',
        ),
        migrations.RemoveField(
            model_name='landingpage',
            name='email_contato',
        ),
        migrations.RemoveField(
            model_name='landingpage',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='landingpage',
            name='gmaps_link',
        ),
        migrations.RemoveField(
            model_name='landingpage',
            name='horario_atendimento',
        ),
        migrations.RemoveField(
            model_name='landingpage',
            name='numeros_telefone',
        ),
        migrations.RemoveField(
            model_name='landingpage',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='landingpage',
            name='reviews_link',
        ),
    ]
