# Generated by Django 4.2.9 on 2024-02-27 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0018_remove_landingpage_categoria_servico_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landingpage',
            name='link_loja',
        ),
        migrations.AddField(
            model_name='empresa',
            name='website',
            field=models.CharField(blank=True, help_text='Nome do botão e link para para site externo. Conheça nossa Loja Virtual#https://minhaloja.com.br', max_length=150),
        ),
    ]
