# Generated by Django 4.2.9 on 2024-01-25 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpagedata',
            name='colunas_items',
            field=models.TextField(help_text='Subtitulos # conteúdo # (cada dupla vira uma coluna no layout final)'),
        ),
        migrations.AlterField(
            model_name='landingpagedata',
            name='descricao_curta',
            field=models.CharField(help_text='Resuma em uma sentença curta o que a empresa faz', max_length=100),
        ),
        migrations.AlterField(
            model_name='landingpagedata',
            name='email_contato',
            field=models.EmailField(blank=True, help_text='Digite o email da empresa, se houver', max_length=254),
        ),
        migrations.AlterField(
            model_name='landingpagedata',
            name='endereco',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
