# Generated by Django 4.2.9 on 2024-01-25 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_pages', '0002_alter_landingpagedata_colunas_items_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=100, unique=True)),
                ('view_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ModelView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='landingpagedata',
            name='nome_empresa',
            field=models.CharField(help_text='Servirá como título da Página', max_length=30),
        ),
        migrations.AlterField(
            model_name='landingpagedata',
            name='num_imagens_carrousel',
            field=models.IntegerField(help_text='O número de imagens no carrossel'),
        ),
    ]
