# Generated by Django 4.2.9 on 2024-01-25 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_pages', '0003_modelroute_modelview_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpagedata',
            name='gmaps_link',
            field=models.URLField(max_length=500),
        ),
    ]
