# Generated by Django 4.2.9 on 2024-01-26 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing_pages', '0004_alter_landingpagedata_gmaps_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModelRoute',
        ),
        migrations.DeleteModel(
            name='ModelView',
        ),
    ]
