# Generated by Django 4.2.9 on 2024-01-30 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loja',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Uma descrição que vai aparecer para o usuário durante a busca', max_length=160),
        ),
        migrations.AlterField(
            model_name='loja',
            name='nome_empresa',
            field=models.CharField(help_text='Servirá como título da página', max_length=50),
        ),
    ]
