# Generated by Django 4.2.9 on 2024-01-26 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lojadata',
            name='link_facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='lojadata',
            name='link_intagram',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='lojadata',
            name='produtos',
            field=models.TextField(help_text='Informações do produto passadas no formato Json. Ex:                                {"pizza": [["Pizza de Calabresa", "Calabresa, Queijo Chedar e massa especial", 59.90, "01.jpg"]\\]}'),
        ),
    ]
