# Generated by Django 4.2.9 on 2024-01-26 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0002_lojadata_link_facebook_lojadata_link_intagram_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lojadata',
            old_name='link_intagram',
            new_name='link_instagram',
        ),
    ]
