# Generated by Django 4.2.9 on 2024-01-26 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0003_rename_link_intagram_lojadata_link_instagram'),
    ]

    operations = [
        migrations.AddField(
            model_name='lojadata',
            name='link_whats',
            field=models.URLField(blank=True),
        ),
    ]
