# Generated by Django 4.2.9 on 2024-01-27 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0004_lojadata_link_whats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lojadata',
            name='link_whats',
            field=models.URLField(blank=True, help_text='https://api.whatsapp.com/send?phone=SEU_NUMERO_DE_TELEFONE'),
        ),
    ]
