# Generated by Django 4.2.9 on 2024-01-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPageData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_cadastrado', models.CharField(help_text='O endereço final do link da página', max_length=50)),
                ('num_imagens_carrousel', models.IntegerField(help_text='O número de imagens no carrossel')),
                ('caminho_de_arquivos', models.CharField(help_text='cidade/nome_da_empresa', max_length=100)),
                ('nome_empresa', models.CharField(help_text='Servirá como título da Página', max_length=30)),
                ('descricao_curta', models.CharField(help_text='Resuma em uma sentença curta o que a empresa faz', max_length=100)),
                ('meta_description', models.CharField(help_text='Uma descrição que vai aparecer para o usuário durante a busca', max_length=160)),
                ('lista_titulo', models.CharField(help_text='Pode ser usado o título: "Produtos e Serviços"', max_length=50)),
                ('lista_items', models.TextField(help_text='Digite os itens da lista de produtos ou serviços separados por vírgula')),
                ('colunas_items', models.TextField(help_text='Subtitulos # conteúdo # (cada dupla vira uma coluna no layout final)')),
                ('numeros_telefone', models.CharField(help_text='Digite os números de telefone', max_length=50)),
                ('email_contato', models.EmailField(blank=True, help_text='Digite o email da empresa, se houver', max_length=254)),
                ('endereco', models.CharField(blank=True, max_length=100)),
                ('horario_atendimento', models.CharField(help_text='Digite o horário de atendimento', max_length=100)),
                ('whats_link', models.URLField(blank=True)),
                ('reviews_link', models.URLField(blank=True)),
                ('gmaps_link', models.URLField(blank=True, max_length=500)),
            ],
        ),
    ]
