# Generated by Django 4.2.9 on 2024-01-29 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco_bucket', models.CharField(help_text='https://gjvoxpezczvyqbnmonap.supabase.co/storage/v1/object/public/conecta_bucket/', max_length=200)),
                ('on_air', models.BooleanField(help_text='Indica se a página está no ar.')),
                ('url_cadastrado', models.CharField(help_text='O endereço final do link da página', max_length=50)),
                ('meta_description', models.CharField(blank=True, help_text='Uma descrição que vai aparecer para o usuário durante a busca', max_length=160)),
                ('nome_empresa', models.CharField(help_text='Servirá como título da Página', max_length=50)),
                ('link_whats', models.URLField(blank=True, help_text='https://api.whatsapp.com/send?phone=SEU_NUMERO_DE_TELEFONE')),
                ('link_instagram', models.URLField(blank=True)),
                ('link_facebook', models.URLField(blank=True)),
                ('nomes_arquivos_imagens', models.CharField(blank=True, help_text='Links para os arquivos, separados por virgula', max_length=300)),
                ('descricao_curta', models.CharField(help_text='Resuma em uma sentença curta o que a empresa faz', max_length=100)),
                ('lista_titulo', models.CharField(blank=True, help_text='Pode ser usado o título: "Produtos e Serviços"', max_length=50)),
                ('lista_items', models.TextField(blank=True, help_text='Digite os itens da lista de produtos ou serviços separados por #')),
                ('colunas_items', models.TextField(blank=True, help_text='Subtitulos # conteúdo # (cada dupla vira uma coluna no layout final)')),
                ('numeros_telefone', models.CharField(blank=True, help_text='Digite os números de telefone', max_length=50)),
                ('email_contato', models.EmailField(blank=True, help_text='Digite o email da empresa, se houver', max_length=254)),
                ('endereco', models.CharField(blank=True, max_length=100)),
                ('horario_atendimento', models.CharField(blank=True, help_text='Digite o horário de atendimento', max_length=100)),
                ('link_loja', models.URLField(blank=True)),
                ('reviews_link', models.URLField(blank=True)),
                ('gmaps_link', models.URLField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'Registro de Landing Page',
                'verbose_name_plural': 'Registros de Landing Pages',
            },
        ),
    ]
