# Generated by Django 4.2.9 on 2024-01-30 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpage',
            name='colunas_items',
            field=models.TextField(blank=True, help_text='Conteúdo adicional no formato de dict. {"key": "value", "key2": "value2"}'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='email_contato',
            field=models.EmailField(blank=True, help_text='Email da empresa, se houver', max_length=254),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='endereco',
            field=models.CharField(blank=True, help_text='Endereço ou região da ede da empresa', max_length=100),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='gmaps_link',
            field=models.URLField(blank=True, help_text="Link para os mapas 'embedded' no formato 'https:\\....br' ", max_length=500),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='horario_atendimento',
            field=models.CharField(blank=True, help_text='Horário de funcionamento', max_length=100),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='link_loja',
            field=models.URLField(blank=True, help_text='Link para loja virtual, se houver'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='lista_items',
            field=models.TextField(blank=True, help_text='Itens da lista em formato de list ["abc", "cde"], ["efg"]'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='lista_titulo',
            field=models.CharField(blank=True, help_text='Título da lista. Ex: "Produtos e Serviços"', max_length=50),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='nome_empresa',
            field=models.CharField(help_text='Servirá como título da página', max_length=50),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='nomes_arquivos_imagens',
            field=models.CharField(blank=True, help_text='nomes dos arquivos, separados por virgula', max_length=300),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='numeros_telefone',
            field=models.CharField(blank=True, help_text='Números de telefone no formato (12) 98765 4321', max_length=50),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='reviews_link',
            field=models.URLField(blank=True, help_text='Link para os reviews do google, se houver'),
        ),
    ]
