# Generated by Django 4.2.9 on 2024-01-26 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpagedata',
            name='link_loja',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='landingpagedata',
            name='nome_empresa',
            field=models.CharField(help_text='Servirá como título da Página', max_length=50),
        ),
    ]
