# Generated by Django 4.2.9 on 2024-02-02 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpages', '0002_alter_landingpage_colunas_items_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpage',
            name='lista_items',
            field=models.TextField(blank=True, help_text='Itens da lista em formato de list ["abc", "cde"]'),
        ),
    ]
