# Generated by Django 4.2.9 on 2024-01-27 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpages', '0002_landingpagedata_link_loja_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpagedata',
            name='imagem',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='landingpagedata',
            name='whats_link',
            field=models.URLField(blank=True, help_text='https://api.whatsapp.com/send?phone=SEU_NUMERO_DE_TELEFONE'),
        ),
    ]
