# Generated by Django 4.2.9 on 2024-01-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpages', '0003_landingpagedata_imagem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landingpagedata',
            name='imagem',
        ),
        migrations.AddField(
            model_name='landingpagedata',
            name='imagem_local',
            field=models.ImageField(blank=True, upload_to='imagens_produtos/'),
        ),
        migrations.AddField(
            model_name='landingpagedata',
            name='imagens',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='landingpagedata',
            name='lista_items',
            field=models.TextField(help_text='Digite os itens da lista de produtos ou serviços separados por #'),
        ),
    ]
