# Generated by Django 4.2.9 on 2024-01-27 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpages', '0004_remove_landingpagedata_imagem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpagedata',
            name='imagem_local',
            field=models.FileField(blank=True, upload_to='arquivos_teste/'),
        ),
    ]
