# Generated by Django 4.2.9 on 2024-01-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpages', '0006_landingpagedata_arquivos_local_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landingpagedata',
            name='arquivos_local',
        ),
        migrations.RemoveField(
            model_name='landingpagedata',
            name='imagem_local',
        ),
        migrations.RemoveField(
            model_name='landingpagedata',
            name='imagens',
        ),
        migrations.AddField(
            model_name='landingpagedata',
            name='imagens_links',
            field=models.TextField(blank=True, help_text='Links para os arquivos, separados por virgula'),
        ),
    ]
