# Generated by Django 4.2.9 on 2024-01-27 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpages', '0007_remove_landingpagedata_arquivos_local_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landingpagedata',
            old_name='imagens_links',
            new_name='nomes_arquivos_imagens',
        ),
        migrations.RemoveField(
            model_name='landingpagedata',
            name='caminho_de_arquivos',
        ),
        migrations.AddField(
            model_name='landingpagedata',
            name='endereco_bucket',
            field=models.CharField(blank=True, help_text='cidade/nome_da_empresa', max_length=200),
        ),
    ]
