# Generated by Django 4.2.9 on 2024-01-27 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpages', '0009_alter_landingpagedata_endereco_bucket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landingpagedata',
            name='num_imagens_carrousel',
        ),
    ]
