# Generated by Django 4.2.9 on 2024-01-28 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpages', '0010_remove_landingpagedata_num_imagens_carrousel'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpagedata',
            name='on_air',
            field=models.BooleanField(default=True, help_text='Indica se a página está no ar.'),
            preserve_default=False,
        ),
    ]
