# Generated by Django 4.2.9 on 2024-01-28 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpages', '0011_landingpagedata_on_air'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='landingpagedata',
            options={'verbose_name': 'Registro de Landing Pages'},
        ),
        migrations.AlterField(
            model_name='landingpagedata',
            name='colunas_items',
            field=models.TextField(blank=True, help_text='Subtitulos # conteúdo # (cada dupla vira uma coluna no layout final)'),
        ),
        migrations.AlterField(
            model_name='landingpagedata',
            name='endereco_bucket',
            field=models.CharField(help_text='https://gjvoxpezczvyqbnmonap.supabase.co/storage/v1/object/public/conecta_bucket/', max_length=200),
        ),
        migrations.AlterField(
            model_name='landingpagedata',
            name='horario_atendimento',
            field=models.CharField(blank=True, help_text='Digite o horário de atendimento', max_length=100),
        ),
        migrations.AlterField(
            model_name='landingpagedata',
            name='lista_items',
            field=models.TextField(blank=True, help_text='Digite os itens da lista de produtos ou serviços separados por #'),
        ),
        migrations.AlterField(
            model_name='landingpagedata',
            name='lista_titulo',
            field=models.CharField(blank=True, help_text='Pode ser usado o título: "Produtos e Serviços"', max_length=50),
        ),
        migrations.AlterField(
            model_name='landingpagedata',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Uma descrição que vai aparecer para o usuário durante a busca', max_length=160),
        ),
        migrations.AlterField(
            model_name='landingpagedata',
            name='nomes_arquivos_imagens',
            field=models.CharField(blank=True, help_text='Links para os arquivos, separados por virgula', max_length=300),
        ),
        migrations.AlterField(
            model_name='landingpagedata',
            name='numeros_telefone',
            field=models.CharField(blank=True, help_text='Digite os números de telefone', max_length=50),
        ),
    ]
